### ISSUE TITLE
can't set vtfcmd without setting output without setting vtfcmd

### ISSUE THREAD

**Issue by DerpyTheHedgeone** [TeamPopplio/vmt-to-vmat#1]
i have no idea what i'm doing wrong here because i'm setting the path to vtfcmd but i can't set it unless i set the output folder but when i set the output folder i must set the vtfcmd.exe path so i'm stuck in a loop but i doubt i can get help
![image](https://user-images.githubusercontent.com/93553944/187083312-c3189129-2b36-47a5-98b7-8ed9b20efe7f.png)

**Comment by TeamPopplio** [comment]
Try setting both variables at the same time, like so:

```batch
vmttovmat --vmtcmd "path/to/vmtcmd.exe" --output "path/to/output/"
```
Let me know how this works out as I haven't updated this tool in quite a while.

**Comment by DerpyTheHedgeone** [comment]
![image](https://user-images.githubusercontent.com/93553944/187090701-8637bf10-60f9-4bac-8ae2-4d680934620d.png)
this either does not work or i'm doing something wrong
do you know any other program that can help me?
